kind: pipeline
type: kubernetes
name: shop

steps:
  - name: test
    image: golang:1.16.15
    environment:
      GOPROXY: https://goproxy.cn,direct
    volumes:
      - name: deps
        path: /go
    commands:
      - go get -d -t ./...
      - go test -v ./...
  - name: build
    image: golang:1.16.15-alpine3.15
    environment:
      GOPROXY: https://goproxy.cn,direct
    volumes:
      - name: deps
        path: /go
    commands:
      - go build ./internal/service/${DRONE_STAGE_NAME}/cmd/main.go -o ${DRONE_STAGE_NAME}
  - name: publishDocker
    image: plugins/docker
    settings:
      username:
        from_secret: ALI_USERNAME
      password:
        from_secret: ALI_DOCKER_PASSWORD
      build_args:
        - serviceName: ${DRONE_STAGE_NAME}
      dockerfile: ./deploy/Dockerfile
      registry: registry.cn-hangzhou.aliyuncs.com
      repo: registry.cn-hangzhou.aliyuncs.com/hyy_yu/${DRONE_REPO_NAME}
      auto_tag: true
    when:
      branch:
        - master
      event:
        - tag
  - name: publishCharts
    image: golang:1.16.15
    environment:
      GOPROXY: https://goproxy.cn,direct
      GITHUB_USER:
        from_secret: GITHUB_USER
      GITHUB_PASSWORD:
        from_secret: GITHUB_PASSWROD
    commands:
      - cd /tmp
      - git config --global user.name feng.yu
      - git config --global user.email 690174435@qq.com
      - git clone https://$GITHUB_USER:$GITHUB_PASSWORD@github.com/HYY-yu/seckill.${DRONE_STAGE_NAME}.chart.git
      - cd seckill.${DRONE_STAGE_NAME}.chart
      - current_version=$(cat Chart.yaml | grep "version" | awk '{ print $2 }' | sed 's/-dev[a-z,0-9]*//')
      - echo "Current chart version: $current_version"
      - chart_version=${DRONE_TAG}
      - echo "Using chart version $chart_version"
      - "cat Chart.yaml | sed 's/version.*/version: $chart_version/'  | sed 's/appVersion.*/appVersion: $tag/' > /tmp/Chart.yaml.patched"
      - cp /tmp/Chart.yaml.patched Chart.yaml
      - git add -all
      - git commit -m "Automated deployment of chart version $chart_version"
      - git push origin main

trigger:
  branch:
    - master
    - dev
  event:
    - push
volumes:
  - name: deps
    temp: {}

