[jwt]
expireDuration = 24
secret = "i1ydX9RtHyuJTrw7frcu"

[mysql]
[mysql.base]
connMaxLifeTime = 60
maxIdleConn = 60
maxOpenConn = 10
addr = "127.0.0.1:3306"
name = "seckill"
pass = "root"
user = "root"

[redis]
addr = "127.0.0.1:6379"
db = "0"
maxRetries = 3
minIdleConns = 5
pass = "redis"
poolSize = 10

[log]
logPath = "./sk-shop-goods.log"
level = "debug" # DEBUG INFO WARN ERROR
stdout = true

[server]
serverName = "sk_shop_goods"
host = ":8081"
pprof = true

[jaeger]
udpEndpoint="http://localhost:14268/api/traces"