[jwt]
expireDuration = 24
secret = "i1ydX9RtHyuJTrw7frcu"

[mysql]
[mysql.base]
connMaxLifeTime = 60
maxIdleConn = 60
maxOpenConn = 10
addr = "mysql-0.mysql.mysql.svc.cluster.local:3306"
name = "seckill"
pass = "root"
user = "root"

[redis]
addr = "redis.mysql.svc.cluster.local:6379"
db = "0"
maxRetries = 3
minIdleConns = 5
pass = "123456"
poolSize = 10

[log]
logPath = "./sk-shop-goods.log"
level = "DEBUG" # DEBUG INFO WARN ERROR
stdout = true
jsonFormat = true

[server]
serverName = "sk_shop_goods"
host = ":8081"
pprof = true
[server.grpc]
host = ":8082"

[jaeger]
udpEndpoint = "http://tempo.kube-ops.svc.cluster.local:14268/api/traces"
stdOut = false