// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package api

import (
	"github.com/HYY-yu/seckill.pkg/cache_v2"
	"github.com/HYY-yu/seckill.pkg/db"
	"go.uber.org/zap"

	"github.com/HYY-yu/seckill.shop/internal/service/shop/api/grpc_handler"
	"github.com/HYY-yu/seckill.shop/internal/service/shop/api/handler"
	"github.com/HYY-yu/seckill.shop/internal/service/shop/api/repo"
	"github.com/HYY-yu/seckill.shop/internal/service/shop/api/svc"
)

// Injectors from wire.go:

// initHandlers init Handlers.
func initHandlers(l *zap.Logger, d db.Repo, c cache_v2.Repo) (*Handlers, error) {
	goodsRepo := repo.NewGoodsRepo()
	goodsSvc := svc.NewGoodsSvc(d, c, goodsRepo)
	goodsHandler := handler.NewGoodsHandler(goodsSvc)
	grpc_handlerGoodsHandler := grpc_handler.NewGoodsHandler(l, goodsSvc)
	handlers := NewHandlers(goodsHandler, grpc_handlerGoodsHandler)
	return handlers, nil
}
