// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package api

import (
	"github.com/HYY-yu/seckill/internal/pkg/cache"
	"github.com/HYY-yu/seckill/internal/pkg/db"
	"github.com/HYY-yu/seckill/internal/service/goods/api/controller"
	"github.com/HYY-yu/seckill/internal/service/goods/api/repo"
	"github.com/HYY-yu/seckill/internal/service/goods/api/svc"
	"go.uber.org/zap"
)

// Injectors from wire.go:

// initControllers init Controllers.
func initControllers(l *zap.Logger, d db.Repo, c cache.Repo) (*Controllers, error) {
	goodsRepo := repo.NewGoodsRepo(l, d)
	goodsSvc := svc.NewGoodsSvc(l, d, c, goodsRepo)
	goodsController := controller.NewGoodsController(goodsSvc)
	controllers := NewControllers(goodsController)
	return controllers, nil
}
