// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
//+build !wireinject

package api

import (
	"github.com/HYY-yu/seckill/internal/pkg/cache"
	"github.com/HYY-yu/seckill/internal/pkg/db"
	"github.com/HYY-yu/seckill/internal/service/api/controller"
	"github.com/HYY-yu/seckill/internal/service/api/repo"
	"github.com/HYY-yu/seckill/internal/service/api/svc"
	"go.uber.org/zap"
)

// Injectors from wire.go:

// initControllers init Controllers.
func initControllers(l *zap.Logger, d db.Repo, c cache.Repo) (*Controllers, error) {
	shopRepo := repo.NewShopRepo(l, d)
	shopSvc := svc.NewShopSvc(l, d, c, shopRepo)
	shopController := controller.NewShopController(shopSvc)
	controllers := NewControllers(shopController)
	return controllers, nil
}
